### ISSUE TITLE
升级Xcode6.4后，貌似用此插件无法恢复之前安装的插件。

### ISSUE THREAD

**Issue by sauchye** [cikelengfeng/RPAXU#2]
升级Xcode6.4后，貌似用此插件无法恢复之前安装的插件。显示安装成功，但是重启Xcode还是无法使用插件。

Xcode DVTPlugInCompatibilityUUID is 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90
write DVTPlugInCompatibilityUUID to /Users/sauchye/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ACCodeSnippetRepository.xcplugin succeed!
...

---

更新
重新安装插件了

**Comment by cikelengfeng** [comment]
@sauchye 抱歉才来回复你。
你的所有插件不能用还是只有ACCodeSnippetRepository不能用？

**Comment by sauchye** [comment]
@cikelengfeng 没事，之前Xcode升级，解决插件问题，一直采用您的开源插件，用着很顺手，在此感谢！感谢您的开源精神，我自己Mac Xcode升级到6.4 用你的插件轻松找回插件，但是公司的则不行；试过好多方法，无奈只好删除之前的插件，重新配置，现已搞定，多谢~
